### ISSUE TITLE
Invalid memory address error

### ISSUE THREAD

**Issue by alepacheco** [tebeka/selenium#36]
The following code produce the following error that shouldn't happen
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x80491b7]

goroutine 1 [running]:
panic(0x8248ba0, 0x1860c010)
	/usr/lib/go/src/runtime/panic.go:500 +0x331
main.main()
	/home/user/projects/selenium.go:12 +0x1b7
exit status 2

```

```
caps := selenium.Capabilities{"browserName": "firefox"}   
wd, _ := selenium.NewRemote(caps, "")
defer wd.Quit()
wd.Get("http://www.google.com")
elem, _ := wd.FindElement(selenium.ByName, "q")
elem.SendKeys("Working")
elem.Submit()

```

**Comment by tebeka** [comment]
Thanks for reporting. Will take a look soon-ish

**Comment by tebeka** [comment]
@alepacheco You need the selenium server running (a Java application). If you add error handing to your program you'll see the issue:

```go
package main

import (
	"log"

	"github.com/tebeka/selenium"
)

func main() {
	caps := selenium.Capabilities{"browserName": "firefox"}
	wd, err := selenium.NewRemote(caps, "")
	if err != nil {
		log.Fatal(err)
	}
	defer wd.Quit()
	wd.Get("http://www.google.com")
	elem, err := wd.FindElement(selenium.ByName, "q")
	if err != nil {
		log.Fatal(err)
	}
	elem.SendKeys("Working")
	elem.Submit()
}
```

Output I get (when there's no selenium server) is:
```
2016/09/16 15:42:55 Post http://127.0.0.1:4444/wd/hub/session: dial tcp 127.0.0.1:4444: getsockopt: connection refused
```
