### ISSUE TITLE
Panic when going directly to Geckodriver 0.16+

### ISSUE THREAD

**Issue by vania-pooh** [tebeka/selenium#60]
Launched standalone Geckodriver binary and using this client to access it. Getting the following panic because of changed JSON protocol in Geckodriver:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x120c87d]

goroutine 36 [running]:
github.com/tebeka/selenium.(*remoteWD).NewSession(0xc42013e000, 0xc42013e000, 0xc42013a000, 0x13d80b0, 0xc420095778)
 /Users/aandryashin/go/src/github.com/tebeka/selenium/remote.go:334 +0x74d
github.com/tebeka/selenium.NewRemote(0xc420136000, 0x12a63fa, 0x1c, 0xc42013a088, 0xc420136000, 0x0, 0x0)
 /Users/aandryashin/go/src/github.com/tebeka/selenium/remote.go:207 +0xa7
main.openURL(0xc4200b02a0, 0x12a16f0, 0xd)
 /Users/aandryashin/go/src/github.com/aandryashin/seleniun-test/main.go:32 +0x155
created by main.main
 /Users/aandryashin/go/src/github.com/aandryashin/seleniun-test/main.go:22 +0x83
```

**Comment by aandryashin** [comment]
That happens due protocol changes since this release:

https://github.com/mozilla/geckodriver/releases/tag/v0.15.0

**Comment by minusnine** [comment]
Thanks for the report. I've (trivially) reproduced this and am working on a fix.

**Comment by minusnine** [comment]
Sorry for the delay in getting the fix out. Please reopen this issue if you encounter any further problems with upgrading Geckodriver to 0.16+.

**Comment by vania-pooh** [comment]
@minusnine thanks.
